on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Reviewers Auto Assign Action
        uses: kentaro-m/auto-assign-action@v2.0.0
